
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hp
 */
public class Load extends javax.swing.JFrame {

    /**
     * Creates new form Load
     */
     String ids;
     String trucksid;
      String citys;
     DefaultTableModel Truck;
    String off;
    Database ob = new Database();
    DefaultTableModel model1;
     DefaultTableModel model;
    String transf =null;
         String Phonef=null;
         String prif =null;
         String weif =null;
          String loadsf =null;
          String Hnumf =null;
          String fromf =null;
          String tof =null;
          String loadf;
      int index;    
      String  pos="Loaded";
      int check;
       String addr;
       String start;
      
   String joss =   "JossoreTruck";
String Sat ="SatkhiraTruck";
String Siraj ="SirajgonjTruck";
String Fen ="FeniTruck";
  
    public Load() {
        initComponents();
         startFrom();
           Trucklist();
    }
    
     public Load(String office,int c) {
        initComponents();
        check=c;
        off=office;
        bran.setText(office+" Branch");
        startFrom();
        Trucklist();
    }
     
      /* public Load(String office,int c) {
        initComponents();
        check=c;
        off=office;
        bran.setText(office+" Branch");
        startFrom();
    }*/
     
        void Trucklist(){
         String trid,from,now,status; 
          String strFrom1 = "Select * from TruckLocation where location='"+off+"'"; 
            ResultSet rs =null;
         rs=ob.select(strFrom1);
         Truck= (DefaultTableModel) trucklist.getModel();   
              
        Truck.setRowCount(0);
       try {
                while (rs.next())
                {
                   
                         //record=rs1.getInt("ID");
                   System.out.print("3");
                   
                    trid=rs.getString("TruckID");
                    now=rs.getString("location");
                   
                    from=rs.getString("Fromcity");
                     status=rs.getString("position");
                    
                    Object[] objs = {trid,from,now,status};
                   Truck.addRow(objs);
                   
                }   
                    
                    
                    
                    
                 
                
                   }
        catch (SQLException ex) {
                Logger.getLogger(Main_Office.class.getName()).log(Level.SEVERE, null, ex);
            }
         
     }
     
     
             void startFrom(){
        
         
        System.out.print("0");
           
      String strFrom1 = "Select * from Storeoffice where fcity='"+off+"' and tcity<>'"+off+"'"; 
      
      //System.out.print(strFrom);
      ResultSet rs1 =null; 
      
      rs1=ob.select(strFrom1); //jave
     // System.out.print(rs1);
      
          model1= (DefaultTableModel) UpStore.getModel();   
              
        model1.setRowCount(0); 
        
       
        
         System.out.print("1");
         try {
                while (rs1.next())
                {
                   //record=rs1.getInt("ID");
                   System.out.print("3");
                   
                    transf=rs1.getString("transe");
                   
                    Phonef=rs1.getString("fphone");
                     prif=rs1.getString("Price");
                     weif=rs1.getString("Weight");
                    
                     tof=rs1.getString("tcity");
                    loadf=rs1.getString("delivery");
                    System.out.print("2");
                    
                    Object[] objs = {transf,Phonef,prif,weif,tof,loadf};
                    model1.addRow(objs);
                   
                }
               
            } catch (SQLException ex) {
                Logger.getLogger(Main_Office.class.getName()).log(Level.SEVERE, null, ex);
            }
         
        }
     
     
     
     
     
     
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bran = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ccity = new javax.swing.JComboBox();
        id = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        truckid = new javax.swing.JLabel();
        sid = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        decity = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tranid = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        truckc = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        Trucks = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        UpStore = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        trucklist = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Load");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Courier");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Create Secrate ID");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Truck ID");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("To");

        jLabel6.setText("Truck");

        ccity.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ccity.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Jossore", "Satkhira", "Sirajgonj", "Feni" }));

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setText("Check");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("LogOut");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Truck ID");

        truckid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        sid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setText("Secrate Id");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setText("Delevier City");

        decity.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel13.setText("Transection ID");

        jButton4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton4.setText("Load");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        truckc.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        truckc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "JossoreTruck", "SatkhiraTruck", "SirajgonjTruck", "FeniTruck" }));

        Trucks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TransectionId", "To City", "Load"
            }
        ));
        jScrollPane2.setViewportView(Trucks);

        jLabel8.setText("Store");

        jButton5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton5.setText("Clear");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        UpStore.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TrucsectionID", "Phone", "Price", "Width", "To", "Load"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(UpStore);

        jTabbedPane1.addTab("DeliveryList", jScrollPane1);

        trucklist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TruckID", "From", "NowTruck", "Status"
            }
        ));
        jScrollPane3.setViewportView(trucklist);

        jTabbedPane1.addTab("TruckList", jScrollPane3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bran, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(truckc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ccity, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(131, 131, 131)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(truckid, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(decity, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel13)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tranid, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                                    .addComponent(sid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(132, 132, 132)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(297, 297, 297)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(96, 96, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(bran, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ccity, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(truckc, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(58, 58, 58))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(truckid, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(decity, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(9, 9, 9))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(sid, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tranid, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)))
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            
        
        
        
        String strFrom1 = "Select * from TruckLocation where location='"+off+"' and TruckID='"+truckc.getSelectedItem().toString()+"'";  
      
      //System.out.print(strFrom);
      ResultSet rs1 =null; 
      
      rs1=ob.select(strFrom1);
      
     try {
      
      if (rs1.next())
                {
                    
                   
        
       trucksid=truckc.getSelectedItem().toString();
          index=ccity.getSelectedIndex();
        citys=ccity.getSelectedItem().toString();
        ids=id.getText();
      int check=checkinput();
        if(check==1){
      
        
        if(!citys.equals(off)){
       load();
          set(trucksid,citys,ids);
    }
        else{
            JOptionPane.showMessageDialog(null,"Truck in city","Error",JOptionPane.ERROR_MESSAGE);
        }
        }
        
       //else{
         //   JOptionPane.showMessageDialog(null,"Empty Secret Code","Error",JOptionPane.ERROR_MESSAGE);
      //  }
        
                }
      
      else{
            JOptionPane.showMessageDialog(null,"The truck is not in "+off+"","Error",JOptionPane.ERROR_MESSAGE);
        }
     }
        catch (SQLException ex) {
                Logger.getLogger(Main_Office.class.getName()).log(Level.SEVERE, null, ex);
            }
     
     
     
        
   
        
    }//GEN-LAST:event_jButton1ActionPerformed
          void set(String trucksid,String citys,String ids){
            
              truckid.setText(trucksid);
              sid.setText(ids);
              decity.setText(citys);
              
               String str = "delete from TruckLocation where location='"+off+"' and TruckID='"+trucksid+"'"; 
         ob.delete(str);
         
           String strn = "insert into TruckLocation(TruckID,location,position,Fromcity,Scode) values('"+truckid.getText()+"','"+decity.getText()+"','"+pos+"','"+off+"','"+sid.getText()+"')";
         ob.insert(strn) ;
            
              
              
           }
    
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         
        
        
        
        
       String tru= truckid.getText();
       String dis=    sid.getText();
       
        String tid=tranid.getText();
       String Citys= decity.getText();
       String truc=truckc.getSelectedItem().toString();
     
      String lfname;
         String     lfuser;
            String  lfphone;
           String    lfcity;
           String    ltname;
           String    ltphone;
           String    ltcity;
           String       ltranse;
          String   ltoParcel;
          String   lmonth;
            String  lday;
              String  lyear;
           String  lweight;
          String   lprice;
           String    ldelivery;
           String   ltrucode;
           String   ltroad;
            String  lthnum;
           String   ltlan; 
      int check= checkinput();
     System.out.print("3");
      try {
      
        if(check ==1){
      
            
     String started = "Select * from TruckLocation where Start='"+start+"' and Scode='"+sid.getText()+"' and location='"+decity.getText()+"'";
      ResultSet  rs =null; 
        rs=ob.select(started);      
            System.out.print(Citys);
       if (rs.next())
                {
            
            
           String strFrom = "Select * from Storeoffice where fcity='"+off+"' and tcity<>'"+off+"' and transe='"+tranid.getText()+"'";
        System.out.print(strFrom);
       
        rs =null; 
        rs=ob.select(strFrom);
        System.out.print(rs);
        if (rs.next())
                {
                lfname=rs.getString("FName");
                System.out.print( lfname);
                lfuser=rs.getString("Fuser");
                lfphone=rs.getString("fphone");
                lfcity=rs.getString("fcity");
               ltname=rs.getString("tname");
                ltphone=rs.getString("tphone");
               ltcity=rs.getString("tcity");
                ltranse=rs.getString("transe");
                ltoParcel=rs.getString("toParcel");
                lday=rs.getString("day");
                 lmonth=rs.getString("month");
                 lyear=rs.getString("year");
                   lweight=rs.getString("weight"); 
                   lprice=rs.getString("price");
                    ldelivery="Loaded";
                   
                   // ltrucode=rs.getString("");
                   ltroad=rs.getString("troad");
                  lthnum=rs.getString("thnum");
                  ltlan=rs.getString("tlan");  
                  
                 // FName,Fuser,fphone,fcity,tname,tphone,troad,thnum,tlan,tcity,transe,toParcel,day,month,year,weight,price
        
     if(/*index==0 && */truc.equals(joss) && Citys.equals(ltcity)){ 
         
         
                  
       String sql = "insert into JossoreTruck (FName,Fuser,fphone,fcity,tname,tphone,troad,thnum,tlan,tcity,transe,toParcel,day,month,year,weight,price,delivery,TruckCode,SiCode) values('"+lfname+"','"+lfuser+"','"+lfphone+"','"+lfcity+"','"+ltname+"','"+ltphone+"','"+ ltroad+"','"+lthnum+"','"+ ltlan+"','"+ltcity+"','"+ltranse+"','"+ltoParcel+"','"+lday+"','"+lmonth+"','"+lyear+"','"+lweight+"','"+lprice+"','"+ldelivery+"','"+truckid.getText()+"','"+sid.getText()+"')";             
      ob.insert(sql) ;
         JOptionPane.showMessageDialog(null,"loaded","Success",JOptionPane.INFORMATION_MESSAGE); 
         
         String str = "delete from Storeoffice where fcity='"+off+"' and tcity<>'"+off+"' and transe='"+tranid.getText()+"'";
         ob.delete(str);
         // String strn = "insert into Truck (TruckID,secretID,location,position,Fromcity) values('"+truckid.getText()+"','"+sid.getText()+"','"+ltcity+"','"+pos+"','"+lfcity+"')";
         //ob.insert(strn) ;
         
           load();
         
       String delivery = "insert into Deli(FName,Fuser,fphone,fcity,tname,tphone,troad,thnum,tlan,tcity,transe,toParcel,day,month,year,weight,price,delivery,TruckCode,SIcode) values('"+lfname+"','"+lfuser+"','"+lfphone+"','"+lfcity+"','"+ltname+"','"+ltphone+"','"+ ltroad+"','"+lthnum+"','"+ ltlan+"','"+ltcity+"','"+ltranse+"','"+ltoParcel+"','"+lday+"','"+lmonth+"','"+lyear+"','"+lweight+"','"+lprice+"','"+ldelivery+"','"+truckid.getText()+"','"+sid.getText()+"')";  
      ob.insert(delivery) ;  
     }
     
       else if(truc.equals(Sat)&& Citys.equals(ltcity)){             
                  
       String sql = "insert into SatkhiraTruck(FName,Fuser,fphone,fcity,tname,tphone,troad,thnum,tlan,tcity,transe,toParcel,day,month,year,weight,price,delivery,TruckCode,SiCode) values('"+lfname+"','"+lfuser+"','"+lfphone+"','"+lfcity+"','"+ltname+"','"+ltphone+"','"+ ltroad+"','"+lthnum+"','"+ ltlan+"','"+ltcity+"','"+ltranse+"','"+ltoParcel+"','"+lday+"','"+lmonth+"','"+lyear+"','"+lweight+"','"+lprice+"','"+ldelivery+"','"+truckid.getText()+"','"+sid.getText()+"')";  
      ob.insert(sql) ;
         JOptionPane.showMessageDialog(null,"loaded","Success",JOptionPane.INFORMATION_MESSAGE); 
         String str = "delete from Storeoffice where fcity='"+off+"' and tcity<>'"+off+"' and transe='"+tranid.getText()+"'";
         ob.delete(str);
        // String strn = "insert into Truck (TruckID,secretID,location,position,Fromcity) values('"+truckid.getText()+"','"+sid.getText()+"','"+ltcity+"','"+pos+"','"+lfcity+"')";
        // ob.insert(strn) ;
         load();
         
         String delivery = "insert into Deli(FName,Fuser,fphone,fcity,tname,tphone,troad,thnum,tlan,tcity,transe,toParcel,day,month,year,weight,price,delivery,TruckCode,SIcode) values('"+lfname+"','"+lfuser+"','"+lfphone+"','"+lfcity+"','"+ltname+"','"+ltphone+"','"+ ltroad+"','"+lthnum+"','"+ ltlan+"','"+ltcity+"','"+ltranse+"','"+ltoParcel+"','"+lday+"','"+lmonth+"','"+lyear+"','"+lweight+"','"+lprice+"','"+ldelivery+"','"+truckid.getText()+"','"+sid.getText()+"')";  
      ob.insert(delivery) ;
     }
      else if(truc.equals(Siraj)&& Citys.equals(ltcity)){             
                  
       String sql = "insert into SirajgonjTruck(FName,Fuser,fphone,fcity,tname,tphone,troad,thnum,tlan,tcity,transe,toParcel,day,month,year,weight,price,delivery,TruckCode,SIcode) values('"+lfname+"','"+lfuser+"','"+lfphone+"','"+lfcity+"','"+ltname+"','"+ltphone+"','"+ ltroad+"','"+lthnum+"','"+ ltlan+"','"+ltcity+"','"+ltranse+"','"+ltoParcel+"','"+lday+"','"+lmonth+"','"+lyear+"','"+lweight+"','"+lprice+"','"+ldelivery+"','"+truckid.getText()+"','"+sid.getText()+"')";  
      ob.insert(sql) ;
         JOptionPane.showMessageDialog(null,"loaded","Success",JOptionPane.INFORMATION_MESSAGE); 
         String str = "delete from Storeoffice where fcity='"+off+"' and tcity<>'"+off+"' and transe='"+tranid.getText()+"'";
         ob.delete(str);
       // String strn = "insert into Truck (TruckID,secretID,location,position,Fromcity) values('"+truckid.getText()+"','"+sid.getText()+"','"+ltcity+"','"+pos+"','"+lfcity+"')";
        // ob.insert(strn) ;
         
           load();
        
         String delivery = "insert into Deli(FName,Fuser,fphone,fcity,tname,tphone,troad,thnum,tlan,tcity,transe,toParcel,day,month,year,weight,price,delivery,TruckCode,SIcode) values('"+lfname+"','"+lfuser+"','"+lfphone+"','"+lfcity+"','"+ltname+"','"+ltphone+"','"+ ltroad+"','"+lthnum+"','"+ ltlan+"','"+ltcity+"','"+ltranse+"','"+ltoParcel+"','"+lday+"','"+lmonth+"','"+lyear+"','"+lweight+"','"+lprice+"','"+ldelivery+"','"+truckid.getText()+"','"+sid.getText()+"')";  
      ob.insert(delivery) ;
     }
     
     else if(truc.equals(Fen)&& Citys.equals(ltcity)){             
                  
       String sql = "insert into FeniTruck(FName,Fuser,fphone,fcity,tname,tphone,troad,thnum,tlan,tcity,transe,toParcel,day,month,year,weight,price,delivery,TruckCode,SIcode) values('"+lfname+"','"+lfuser+"','"+lfphone+"','"+lfcity+"','"+ltname+"','"+ltphone+"','"+ ltroad+"','"+lthnum+"','"+ ltlan+"','"+ltcity+"','"+ltranse+"','"+ltoParcel+"','"+lday+"','"+lmonth+"','"+lyear+"','"+lweight+"','"+lprice+"','"+ldelivery+"','"+truckid.getText()+"','"+sid.getText()+"')";  
      ob.insert(sql) ;
         JOptionPane.showMessageDialog(null,"loaded","Success",JOptionPane.INFORMATION_MESSAGE); 
         String str = "delete from Storeoffice where fcity='"+off+"' and tcity<>'"+off+"' and transe='"+tranid.getText()+"'";
         ob.delete(str);
        // String strn = "insert into Truck (TruckID,secretID,location,position,Fromcity) values('"+truckid.getText()+"','"+sid.getText()+"','"+ltcity+"','"+pos+"','"+lfcity+"')";
        // ob.insert(strn) ;
         
           load();
         
         String delivery = "insert into Deli(FName,Fuser,fphone,fcity,tname,tphone,troad,thnum,tlan,tcity,transe,toParcel,day,month,year,weight,price,delivery,TruckCode,SIcode) values('"+lfname+"','"+lfuser+"','"+lfphone+"','"+lfcity+"','"+ltname+"','"+ltphone+"','"+ ltroad+"','"+lthnum+"','"+ ltlan+"','"+ltcity+"','"+ltranse+"','"+ltoParcel+"','"+lday+"','"+lmonth+"','"+lyear+"','"+lweight+"','"+lprice+"','"+ldelivery+"','"+truckid.getText()+"','"+sid.getText()+"')";  
      ob.insert(delivery) ;
         
     }
      else{
            
           JOptionPane.showMessageDialog(null,"Wrong Transection","Error",JOptionPane.ERROR_MESSAGE); 
        }
         
         startFrom();
                }
        
       
        else{
            
           JOptionPane.showMessageDialog(null,"Wrong TransectionID","Error",JOptionPane.ERROR_MESSAGE); 
        }
       
        /////
        }
        
        
        else{
            
           JOptionPane.showMessageDialog(null,"The is already Gone You r late","Error",JOptionPane.ERROR_MESSAGE); 
        }
        
        }
      
       else{
            
           JOptionPane.showMessageDialog(null,"Empty Transection","Error",JOptionPane.ERROR_MESSAGE); 
        }
      
      
      
      
      }
      
      catch (SQLException ex) {
                Logger.getLogger(Main_Office.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    
    void load(){
        
        
        int selected=truckc.getSelectedIndex();
        
        if(selected==0){
             String truck = "Select * from JossoreTruck";   
            loaded(truck);
            
        }
       else  if(selected==1){
             String truck = "Select * from SatkhiraTruck";   
            loaded(truck);
        }
        else  if(selected==2){
             String truck = "Select * from SirajgonjTruck ";   
            loaded(truck);
        }
        else   if(selected==3){
             String truck = "Select * from FeniTruck";   
            loaded(truck);
        }
        else{
            
        }
        
        
      tranid.setText("");
        
    }
      
    void loaded(String truck){
    
    
        System.out.print("0");
           
      
      
      //System.out.print(strFrom);
      ResultSet rs1 =null; 
      
      rs1=ob.select(truck); //jave
     // System.out.print(rs1);
      
        model= (DefaultTableModel) Trucks.getModel();   
              
        model.setRowCount(0); 
        
        //model= (DefaultTableModel) pro.getModel();   
              
        //model.setRowCount(0); 
        
         System.out.print("1");
         try {
                while (rs1.next())
                {
                   //record=rs1.getInt("ID");
                   System.out.print("3");
                   
                    transf=rs1.getString("transe");
                   
                     tof=rs1.getString("tcity");
                    loadf=rs1.getString("delivery");
                    System.out.print("2");
                    
                    Object[] objs = {transf,tof,loadf};
                    model.addRow(objs);
                   
                }
        
    }
          catch (SQLException ex) {
                Logger.getLogger(Main_Office.class.getName()).log(Level.SEVERE, null, ex);
            }
    
    }
    
    
    
    
    
    
    
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
 
        start="GO";
        
        
         
          String trucks= "update TruckLocation SET Start= '"+start+"' where Fromcity='"+off+"' and location='"+decity+"' and Scode='"+sid.getText()+"'";
         ob.update(trucks);
         
         JOptionPane.showMessageDialog(null,"loaded Successfull ","the is Run",JOptionPane.INFORMATION_MESSAGE);
         System.out.print(trucks);
        
        System.out.print(trucks);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    if(check==0){
        Main_Office ob1=new Main_Office(off);
       ob1.setVisible(true);
       dispose();
        }
        else{
            
           Authority ob1=new Authority(off,addr);
       ob1.setVisible(true);
       dispose(); 
        }       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        LogIn ob1=new LogIn();
        ob1.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
      int checkinput(){
          
         if(! truckid.getText().isEmpty() && ! truckid.getText().isEmpty() && ! truckid.getText().isEmpty()) {
             return 1;
         }
         else if(!id.getText().isEmpty()){
             return 1;
         }
         else{
            return 0; 
         }
      }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Load.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Load.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Load.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Load.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Load().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Trucks;
    private javax.swing.JTable UpStore;
    private javax.swing.JLabel bran;
    private javax.swing.JComboBox ccity;
    private javax.swing.JLabel decity;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel sid;
    private javax.swing.JTextField tranid;
    private javax.swing.JComboBox truckc;
    private javax.swing.JLabel truckid;
    private javax.swing.JTable trucklist;
    // End of variables declaration//GEN-END:variables
}
